# Generated by Django 4.1 on 2024-03-02 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('klimadaten', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='station',
            options={'ordering': ['name']},
        ),
    ]
