# Generated by Django 4.1 on 2024-03-13 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klimadaten', '0003_weather'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='max_windspeed',
            field=models.DecimalField(decimal_places=7, max_digits=10, verbose_name='Wind Speed'),
        ),
    ]
